import Link from "next/link"

// import file "global.css"
import "./globals.css"
import Image from "next/image"

// import FontAwesome
import "@fortawesome/fontawesome-svg-core/styles.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="cupcake">
      <body>
        {/* buat area header */}
        <header>
          {/* area image */}
          {/* <img src="/images/logouti.png" alt="logo"></img> */}
          <Image src={"/images/logouti.png"} alt="logo" width={520} height={80} ></Image>

          

          {/* area menu */}
          <nav className="mt-5 flex justify-center">
            <Link href={"/"} className="bg-blue-500 rounded-full text-white px-5 py-2.5 hover:bg-red-500 mr-2 w-64">Data Mahasiswa</Link>
            <Link href={"/"} className="bg-blue-500 rounded-full text-white px-5 py-2.5 hover:bg-red-500 ml-2 w-64">Log Data Mahasiswa</Link>

          </nav>
        </header>

        {/* buat area content */}
        {/* section untuk mengatur tabel */}
        <section className="m-5">
        {children}
        </section>

        {/* buat area footer */}
        <footer className="bg-blue-500 text-white px-5 py-2.5 text-center mt-5 flex justify-center">
          Copyright &copy; 2024 - Mito Rahmandana Wijaya
      </footer>
      </body>
    </html>
  )
}
